drop table if exists bookmarks;

create table bookmarks (
id integer primary key generated by default as identity,
title text not null,
url text not null,
description text default 'One of my favorite sites',
rating integer not null
	check(rating <= 5)
);

insert into bookmarks (title, url, description, rating)
values
('Google', 'www.google.com', 'The most popular search engine in the world.', 5),
('Yahoo Answers', 'answers.yahoo.com', 'I want this one to fail so I can confirm the check rating works.', 6),
('Wikipedia', 'www.wikipedia.org', 'A donation of $2.75 can keep them running for years.', 5),
('Twitter', 'twitter.com', 'Everyone should be allowed to scream into the void.', 3),
('LinkedIn', 'linkedin.com/feed', 'It''s like Facebook but for jobs.', 4),
('Facebook', 'facebook.com', 'It''s like LinkedIn but for nothing.', 3),
('github', 'github.com', 'Put your code here.', 5),
('Netflix', 'www.netflix.com', 'They have replaced telivision.', 4),
('YouTube', 'youtube.com', 'You could learn things here, but will waste time instead.', 5),
('w3schools', 'w3schools.com', null, 5);